### ISSUE TITLE
Manual code review and static code analysis

### ISSUE THREAD

**Issue by gergobuzas** [BME-MIT-IET/iet-hf-2024-lajkabospoverdbyc3tin#1]
Perform manual code review on a part of the application (GitHub, Gerrit...) + Run static analysis tool and review reported bugs (SonarCloud, SpotBugs, VS Code Analyzer, Codacy, Coverity Scan...).

As the tools can find a lot of bugs and warnings, it is enough to review a subset of them and if all team members agree, fix them. Make an effort to examine different types of bug reports, preferably non-trivial ones.

**Comment by zsombi02** [comment]
Manual Code review part is completed, Static analisys is left commit rev 2def853

**Comment by gergobuzas** [comment]
Alright, thank you!

Make sure to rebase your project to main branch before starting static analysis, so it aligns with the current project structure! (We have HwProject/src and HwProject/tests directories now)

Good luck with it, you might need it 😅
