### ISSUE TITLE
Non-functional tests

### ISSUE THREAD

**Issue by gergobuzas** [BME-MIT-IET/iet-hf-2024-lajkabospoverdbyc3tin#5]
Testing of performance, security and usability related properties (JMeter, K6, ...)

**Comment by kristofmoldovan** [comment]
Started writing benchmarks and running them locally, the following plugin will be needed to be added to the dependencies for proper building: https://github.com/melix/jmh-gradle-plugin

**Comment by gergobuzas** [comment]
Alright, thank you!

Before progressing, make sure to rebase your branch to the current main branch, as the project structure changed (HwProject/src and HwProject/tests directories were created)

Good luck with it, you might need it! 😅

**Comment by kristofmoldovan** [comment]
Thanks for the information 😄 I was able to merge the current main branch into mine.

The [benchmark](https://github.com/BME-MIT-IET/iet-hf-2024-lajkabospoverdbyc3tin/tree/kristofmoldovan-NonFunctionalTests/HwProject/tests/benchmark) package is currently under the tests folder on my branch. (Temporaly moved the "HelperClasses" folder inside the package to be able to build locally. I will revert it when the build tools are set up)
